export const ESTIMATED_LIQUIDATION_PRICE = "ESTIMAATED LIQ. PRICE";

export const MAX_ADDABLE_MARGIN = "MAX ADDABLE MARGIN";

export const MAX_REMOVABLE_MARGIN = "MAX REMOVABLE MARGIN";

export const CURR_MARGIN = "CURRENT MARGIN";
