export const POSITIONS_FETCH_FAIL = "POSITIONS_FETCH_FAIL";

export const SET_LEVERAGE_SUCCESS = "SET_LEVERAGE_SUCCESS";
export const SET_LEVERAGE_FAIL = "SET_LEVERAGE_FAIL";

export const SET_MARGIN_TYPE = "SET_MARGIN_TYPE";

export const SET_PROFILE_SUCCESS = "SET_PROFILE_SUCCESS";
export const SET_PROFILE_FAIL = "SET_PROFILE_FAIL";

export const GET_OPEN_INTEREST_SUCCESS = "GET_OPEN_INTEREST_SUCCESS";
export const GET_OPEN_INTEREST_FAIL = "GET_OPEN_INTEREST_FAIL";

export const ERASE_POSITION_DIRECTORY = "ERASE_POSITION_DIRECTORY";

export const SET_TRADABLE_SYMBOL_LIST_FAIL = "SET_TRADABLE_SYMBOL_LIST_FAIL";
export const SET_TRADABLE_SYMBOL_LIST_SUCCESS = "SET_TRADABLE_SYMBOL_LIST_SUCCESS";
export const GET_LEVERAGE_BRACKET_SUCCESS = "GET_LEVERAGE_BRACKET_SUCCESS";
export const GET_LEVERAGE_BRACKET_FAIL = "GET_LEVERAGE_BRACKET_FAIL";

export const SET_SELECTED_SYMBOL_SUCCESS = "SET_SELECTED_SYMBOL_SUCCESS";

export const OPEN_ORDERS_FETCH_SUCCESS = "OPEN_ORDERS_FETCH_SUCCESS";
export const OPEN_ORDERS_FETCH_FAIL = "OPEN_ORDERS_FETCH_FAIL";

export const ORDER_HISTORY_FETCH_SUCCESS = "ORDER_HISTORY_FETCH_SUCCESS";
export const ORDER_HISTORY_FETCH_FAIL = "ORDER_HISTORY_FETCH_FAIL";

export const ALL_ORDER_HISTORY_FETCH_SUCCESS = "ALL_ORDER_HISTORY_FETCH_SUCCESS";
export const ALL_ORDER_HISTORY_FETCH_FAIL = "ALL_ORDER_HISTORY_FETCH_FAIL";

export const TRADE_HISTORY_FETCH_SUCCESS = "TRADE_HISTORY_FETCH_SUCCESS";
export const TRADE_HISTORY_FETCH_FAIL = "TRADE_HISTORY_FETCH_FAIL";

export const TRANSACTION_HISTORY_FETCH_SUCCESS = "TRANSACTION_HISTORY_FETCH_SUCCESS";
export const TRANSACTION_HISTORY_FETCH_FAIL = "TRANSACTION_HISTORY_FETCH_FAIL";

export const FUTURES_ACCOUNT_INFO_FETCH_SUCCESS = "FUTURES_ACCOUNT_INFO_FETCH_SUCCESS";
export const FUTURES_ACCOUNT_INFO_FETCH_FAIL = "FUTURES_ACCOUNT_INFO_FETCH_FAIL";

export const UPDATE_DATE_RANGE_SUCCESS = "UPDATE_DATE_RANGE_SUCCESS";
export const RESET_DATE_RANGE_SUCCESS = "RESET_DATE_RANGE_SUCCESS";

export const OPEN_ORDERS_WEB_STREAM = "OPEN_ORDERS_WEB_STREAM";
export const REMOVE_POSITIONS_QUANT = "REMOVE_POSITIONS_QUANT";

export const ADD_ISOLATED_WALLET_ACCOUNT_UPDATE = "ADD_ISOLATED_WALLET_ACCOUNT_UPDATE";

export const DENSITY_WS_CONNECT = "DENSITY_WS_CONNECT";
export const DENSITY_WS_CONNECTED = "DENSITY_WS_CONNECTED";
export const DENSITY_WS_DISCONNECT = "DENSITY_WS_DISCONNECT";
export const DENSITY_WS_DISCONNECTED = "DENSITY_WS_DISCONNECTED";
export const DENSITY_WS_SUBSCRIBE_CREATE_ORDER = "DENSITY_WS_SUBSCRIBE_CREATE_ORDER";
export const DENSITY_WS_SUBSCRIBE_CLOSE_ORDER = "DENSITY_WS_SUBSCRIBE_CLOSE_ORDER";
export const SET_ORDER_BOOK = " SET_ORDER_BOOK";

export const BINANCE_WS_CONNECT = "BINANCE_WS_CONNECT";
export const BINANCE_WS_DISCONNECT = "BINANCE_WS_DISCONNECT";

export const BINANCE_WS_SUBSCRIBE = "BINANCE_WS_SUBSCRIBE";
export const BINANCE_WS_UNSUBSCRIBE = "BINANCE_WS_UNSUBSCRIBE";

export const DENSITY_WS_OPENED = "DENSITY_WS_OPENED";
export const DENSITY_WS_CLOSED = "DENSITY_WS_CLOSED";

export const BINANCE_WS_OPENED = "BINANCE_WS_OPENED";
export const BINANCE_WS_CLOSED = "BINANCE_WS_CLOSED";

export const INTERNET_ONLINE = "INTERNET_ONLINE";
export const INTERNET_OFFLINE = "INTERNET_OFFLINE";

export const SET_ALL_SYMBOL_DATA_SUCCESS = "SET_ALL_SYMBOL_DATA_SUCCESS";
export const SET_ALL_SYMBOL_DATA_FAIL = "SET_ALL_SYMBOL_DATA_FAIL";

export const AVAILABLE_BALANCE_FETCH_SUCCESS = "AVAILABLE_BALANCE_FETCH_SUCCESS";
export const AVAILABLE_BALANCE_FETCH_FAIL = "AVAILABLE_BALANCE_FETCH_FAIL";

export const SET_LTP_DATA = "SET_LTP_DATA";
export const SET_MARK_PRICE_DATA = "SET_MARK_PRICE_DATA";
export const SET_TICKER_DATA = "SET_TICKER_DATA";
export const SET_MARK_PRICE_ALL_DATA = "SET_MARK_PRICE_ALL_DATA";

export const SET_ALL_TICKER_DATA = "SET_ALL_TICKER_DATA";
export const SET_KLINES_DATA = "SET_KLINES_DATA";
export const UPDATE_KLINES_DATA = "UPDATE_KLINES_DATA";
export const SET_RECENT_USER_TRADES_SUCCESS = "SET_RECENT_USER_TRADES_SUCCESS";
export const SET_RECENT_USER_TRADES_FAIL = "SET_RECENT_USER_TRADES_FAIL";

export const SET_SELECTED_WALLET_SUCCESS = "SET_SELECTED_WALLET_SUCCESS";
export const SET_SELECTED_WALLET_FAIL = "SET_SELECTED_WALLET_FAIL";

export const WALLET_SCREEN_RENDER_SUCCESS = "WALLET_SCREEN_RENDER_SUCCESS";
export const WALLET_SCREEN_RENDER_FAIL = "WALLET_SCREEN_RENDER_FAIL";

export const SET_POSITIONS_DATA = "SET_POSITIONS_DATA";

export const ORDER_CREATION_SUCESS = "ORDER_CREATION_SUCESS";
export const ORDER_CREATION_FAIL = "ORDER_CREATION_FAIL";

export const ORDER_CREATION_TP_SL_SUCESS = "ORDER_CREATION_TP_SL_SUCESS";
export const ORDER_CREATION_TP_SL_FAIL = "ORDER_CREATION_TP_SL_FAIL";

export const UPDATE_ACTIVE_POSITIONS_WEB_STREAM = "UPDATE_ACTIVE_POSITIONS_WEB_STREAM";
export const CREATE_NEW_POSITION_WEB_STREAM = "CREATE_NEW_POSITION_WEB_STREAM";

export const GLOBAL_ERROR_ADD = "GLOBAL_ERROR_ADD";
export const GLOBAL_ERROR_REMOVE = "GLOBAL_ERROR_REMOVE";

export const EXIT_ORDER_SUCCESS = "EXIT_ORDER_SUCCESS";
export const EXIT_ORDER_FAIL = "EXIT_ORDER_FAIL";

export const OPEN_ORDERS_UPDATE_SIZE_STREAM = "OPEN_ORDERS_UPDATE_SIZE_STREAM";
export const OPEN_ORDERS_UPDATE_SIZE_REST = "OPEN_ORDERS_UPDATE_SIZE_REST";

export const SET_DEPTH_UPDATE = "SET_DEPTH_UPDATE";

export const SET_FAVOURITE_SYMBOL = "SET_FAVOURITE_SYMBOL";
export const REMOVE_FAVOURITE_SYMBOL = "REMOVE_FAVOURITE_SYMBOL";

export const GET_USER_WATCHLIST = "GET_USER_WATCHLIST";

export const FETCH_FIAT_BALANCE_FAIL = "FETCH_FIAT_BALANCE_FAIL";

export const FETCH_FIAT_TRANSACTION_HISTORY_HISTORY_FAIL = "FETCH_FIAT_TRANSACTION_HISTORY_HISTORY_FAIL";

export const FETCH_FUTURES_TRANSACTION_HISTORY_FAIL = "FETCH_FUTURES_TRANSACTION_HISTORY_FAIL";

export const FETCH_FUTURES_ACCOUNT_DETAILS_FAIL = "FETCH_FUTURES_ACCOUNT_DETAILS_FAIL";

export const FETCH_FIAT_EXCHANGE_RATE_FAIL = "FETCH_FIAT_EXCHANGE_RATE_FAIL";

export const BUY_USDT_FAIL = "BUY_USDT_FAIL";
export const BUY_USDT_SUCCESS = "BUY_USDT_SUCCESS";

export const SELL_USDT_INITIATE_FAIL = " SELL_USDT_INITIATE_FAIL";

export const SELL_USDT_FAIL = "SELL_USDT_FAIL";
export const SELL_USDT_SUCCESS = "SELL_USDT_SUCCESS";

export const FETCH_DENSITY_BANK_ACCOUNT_FAIL = "FETCH_DENSITY_BANK_ACCOUNT_FAIL";

export const DEPOSIT_FIAT_FAIL = "DEPOSIT_FIAT_FAIL";
export const DEPOSIT_FIAT_SUCCESS = "DEPOSIT_FIAT_SUCCESS";

export const WITHDRAW_FIAT_INITIATE_FAIL = "WITHDRAW_FIAT_INITIATE_FAIL";

export const WITHDRAW_FIAT_FAIL = "WITHDRAW_FIAT_FAIL";
export const WITHDRAW_FIAT_SUCCESS = "WITHDRAW_FIAT_FAIL";

export const ADD_REMOVE_MARGIN_SUCCESS = "ADD_REMOVE_MARGIN_SUCCESS";
export const ADD_REMOVE_MARGIN_FAIL = "ADD_REMOVE_MARGIN_FAIL";

export const SET_LIMIT_PRICE_HANDLER = "SET_LIMIT_PRICE_HANDLER";

export const FETCH_POSITION_RISK_FAIL = " FETCH_POSITION_RISK_FAIL";

export const CREATE_POSIITON_ACCOUNT_INFO = "CREATE_POSIITON_ACCOUNT_INFO";
export const UPDATE_ISOLATED_WALLET_POS_RISK = "UPDATE_ISOLATED_WALLET_POS_RISK";
export const SET_LIQUIDATION_PRICE = "SET_LIQUIDATION_PRICE";
export const SET_LEVERAGE_POS_RISK = "SET_LEVERAGE_POS_RISK";
export const UPDATE_LIQUIDATION_PRICE = "UPDATE_LIQUIDATION_PRICE";

export const BINANCE_WEBSOCKET_CONNECTION = "BINANCE_WEBSOCKET_CONNECTION";
export const BINANCE_WEBSOCKET_SUBSCRIPTION = "BINANCE_WEBSOCKET_SUBSCRIPTION";

export const DENSITY_WEBSOCKET_CONNECTION = "DENSITY_WEBSOCKET_CONNECTION";
export const OPEN_SIDE_MENU = "OPEN_SIDE_MENU_SUCCESS";

export const SET_SHOW_PROFIT_LOSS_BASED_ON = "SET_SHOW_PROFIT_LOSS_BASED_ON";
export const SET_SHOW_PROFIT_LOSS_FEES_ADJUSTED = "SET_SHOW_PROFIT_LOSS_FEES_ADJUSTED";
export const CHANGE_IN_ASSETS__STATE = "CHANGE_IN_ASSETS__STATE";

export const GET_AGGTRADE_SUCCESS = "GET_AGGTRADE_SUCCESS";

export const NEW_KYC_DETAILS = "NEW_KYC_DETAILS";
export const NEW_BANK_DETAILS = "NEW_BANK_DETAILS";
export const API_ORDER_TRIGGER = "API_ORDER_TRIGGER";
export const DELETE_API_ORDER_ID = "DELETE_API_ORDER_ID";
export const WS_ORDER_TRIGGER = "WS_ORDER_TRIGGER";
export const UPDATE_API_ORDER = "UPDATE_API_ORDER";
export const UPDATE_OPEN_ORDER = "UPDATE_OPEN_ORDER";
export const SET_CROSS_WALLET_BALANCE = "SET_CROSS_WALLET_BALANCE";

export const CREATE_API_SUCCESS = "CREATE_API_SUCCESS";
export const CREATE_API_FAIL = "CREATE_API_FAIL";

export const GET_API_TABLE_DATA_SUCCESS = "GET_API_TABLE_DATA_SUCCESS";
export const GET_API_TABLE_DATA_FAIL = "GET_API_TABLE_DATA_FAIL";

export const GET_USER_PREFERENCES_FAIL = "GET_USER_PREFERENCES_FAIL";
export const GET_USER_PREFERENCES_SUCCESS = "GET_USER_PREFERENCES_SUCCESS";
export const GET_USER_PREFERENCES_EMAIL_ALERT_SUCCESS = "GET_USER_PREFERENCES_EMAIL_ALERT_SUCCESS";
export const GET_USER_PREFERENCES_CONFIRMATION_SUCCESS = "GET_USER_PREFERENCES_CONFIRMATION_SUCCESS";
export const ITEMS_REQUESTED = "ITEMS_REQUESTED";
export const ITEMS_RECEIVED = "ITEMS_RECEIVED";

export const GET_PNL_HISTORY_SUCCESS = "GET_PNL_HISTORY_SUCCESS";
export const GET_PNL_HISTORY_FAIL = "GET_PNL_HISTORY_FAIL";

export const SET_UNREALISED_PROFITLOSS = "SET_UNREALISED_PROFITLOSS";
export const SET_UNREALISED_PROFITLOSS_BASED_ON_LTP = "SET_UNREALISED_PROFITLOSS_BASED_ON_LTP";
export const REMOVE_UNREALISED_PROFITLOSS = "REMOVE_UNREALISED_PROFITLOSS";
export const SET_UNREALISED_PROFITLOSS_CROSS = "SET_UNREALISED_PROFITLOSS_CROSS";
export const SET_UNREALISED_PROFITLOSS_CROSS_BASED_ON_LTP = "SET_UNREALISED_PROFITLOSS_CROSS_BASED_ON_LTP";
export const SET_CROSS_WALLET_DETAILS = "SET_CROSS_WALLET_DETAILS";
export const REMOVE_CROSS_WALLET_DETAILS = "REMOVE_CROSS_WALLET_DETAILS";
export const CLEAR_UNREALISED_PROFITLOSS = "CLEAR_UNREALISED_PROFITLOSS";
export const GET_LEVERAGE_SUCCESS = "GET_LEVERAGE_SUCCESS";
export const GET_LEVERAGE_FAIL = "GET_LEVERAGE_FAIL";
export const UPDATE_ISOLATED_WALLET_POSITIONS = "UPDATE_ISOLATED_WALLET_POSITIONS";
export const RESET_POSITION_DIRECTORY = "RESET_POSITION_DIRECTORY";
export const SET_INACTIVE_TIME = "SET_INACTIVE_TIME";
export const IS_LOW_END_DEVICE = "IS_LOW_END_DEVICE";
export const NOT_A_LOW_END_DEVICE = " NOT_A_LOW_END_DEVICE";

// Signal Trading Constants For Reducer Updation
export const SET_LIST_OF_ANALYSTS = "SET_LIST_OF_ANALYSTS";
export const SET_ANALYST_ID = "SET_ANALYST_ID";
export const SET_USER_PERSONNA = "SET_USER_PERSONNA";
export const SET_SYMBOLS_BARRED_FROM_PLACING_A_NEW_ORDER_IF_A_FOLLOWER = "SET_SYMBOLS_BARRED_FROM_PLACING_A_NEW_ORDER_IF_A_FOLLOWER";
export const SET_OVERALL_SIGNAL_TRADING_STATS = "OVERALL_SIGNAL_TRADING_STATS";
export const SET_FOLLOWER_DETAILS = "FOLLOWER_DETAILS";
export const SET_ANALYST_FOLLOWED_BY_THE_FOLLOWER = "SET_ANALYST_FOLLOWED_BY_THE_FOLLOWER";
export const SET_FOLLOWER_STATS = "SET_FOLLOWER_STATS";
export const SET_LIVE_SIGNALS_FOR_FOLLOWERS = "SET_LIVE_SIGNALS_FOR_FOLLOWERS";
export const SET_COMPLETED_SIGNALS_FOR_FOLLOWERS = "SET_COMPLETED_SIGNALS_FOR_FOLLOWERS";
export const SET_REJECTED_SIGNALS_FOR_FOLLOWERS = "SET_REJECTED_SIGNALS_FOR_FOLLOWERS";
export const SET_ANALYST_DETAILS_FOR_SELF = "SET_ANALYST_DETAILS_FOR_SELF";
export const SET_LIVE_SIGNALS_IF_AN_ANALYST = "SET_LIVE_DETAILS_IF_AN_ANALYST";
export const SET_COMPLETED_SIGNALS_IF_AN_ANALYST = "SET_COMPLETED_DETAILS_IF_AN_ANALYST";
export const SET_SIGNAL_LIST_FOR_ANALYST = "SET_SIGNAL_LIST_FOR_ANALYST";
export const SET_TRADING_STATS = "SET_TRADING_STATS";
export const UPDATE_ERROR_COUNT = `UPDATE_ERROR_COUNT`;
export const RESET_ERROR_COUNT = `RESET_ERROR_COUNT`;

export const FALLBACK_HANDLER = "FALLBACK_HANDLER";
export const SET_FAVOURITE_SYMBOLS_IN_VIEWPORT = "SET_FAVOURITE_SYMBOLS_IN_VIEWPORT";

export const CHANGE_FORM_STATE = "CHANGE_FORM_STATE";

export const SET_ALL_SIGNAL_DATA_ADMIN = "SET_ALL_SIGNAL_DATA_ADMIN";
export const SET_ANALYST_SIGNALS_COUNT = "SET_ANALYST_SIGNALS_COUNT";

export const API_SNAPSHOT_UPDATED = "API_SNAPSHOT_UPDATED";

export const ACTIVE_SYMBOLS_MAP = "ACTIVE_SYMBOLS_MAP";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
