export const SIDES_MAP = {
  BUY: "LONG",
  SELL: "SHORT"
};

export const ORDERFORM_CONSTANTS = {
  BUY_LONG_LABEL: "BUY",
  SELL_SHORT_LABEL: "SELL",
  AVAILABLE_BALANCE_LABEL: "Available Balance",
  MINIMUM_QUANTITY_LABEL: "Minimum Qty: ",
  STEP_SIZE_LABEL: "Step Size: ",
  MARGIN_USED_LABEL: "Margin Used",
  LEVERAGE_LABEL: "Leverage",
  MARKET_TYPE_LABEL: "Market",
  LIMIT_TYPE_LABEL: "Limit",
  STOP_MARKET_LABEL: "Stop Market",
  STOP_LIMIT_LABEL: "Stop Limit",
  PERCENTAGE_LABEL_25: "25%",
  PERCENTAGE_LABEL_50: "50%",
  PERCENTAGE_LABEL_75: "75%",
  PERCENTAGE_LABEL_100: "100%",
  REDUCE_ONLY_LABEL: "Reduce Only",
  ENTER_SIZE_IN_USDT_LABEL: "Size in USDT",
  ENTER_SIZE_IN_LABEL: "Size in ",
  ENTER_TRIGGER_PRICE_LABEL: "Trigger price",
  SIZE_LABEL: "Size",
  MAX_BUYING_POWER_LABEL: "Max Buying Power ",
  LEVERAGE_2X: "2x",
  LEVERAGE_3X: "3x",
  LEVERAGE_5X: "5x",
  LEVERAGE_10X: "10x",
  ENTER_LIMIT_PRICE_LABEL: "Limit price",
  PERCENTAGE_LABEL: "%",
  ENTER_TP_LABEL: " Take Profit",
  ENTER_SL_LABEL: "Stop Loss",
  INADEQUATE_MARGIN_LABEL: "Enter Minimum Quantity",
  EXCEEDS_AVAILABLE_BALANCE_LABEL: "Not enough balance to place this trade",
  EXCEEDS_AVAILABLE_BALANCE_COIN_LABEL: "Order Size exceeds for this coin",
  REQUIRED_LABEL: "Required",
  INVALID_TP_LABEL: "Invalid TP",
  INVALID_SL_LABEL: "Invalid SL",
  CONFIRM_LEVERAGE: "Please confirm the leverage first",
  ISOLATED_LABEL: "ISOLATED"
};
