export const WALLET_CONSTANTS = {
  BUY_MODAL_TITLE: "Buy USDT",
  ENTER_AMOUNT_INR_LABEL: "Enter Amount in INR:",
  ENTER_AMOUNT_USDT_LABEL: "Enter amount in USDT:",
  RECEIVE_USDT_LABEL: "You will recieve USDT:",
  RECEIVE_INR_LABEL: "You will recieve:",
  INR_DENOMINATION_LABEL: " INR ",
  UNIT_DENOMINATION_USDT_LABEL: "1 USDT:",
  MAX_LABEL: "MAX",
  SELL_MODAL_TITLE: "Sell USDT",
  REFRESH_LABEL: "Refresh",
  TDS_LABEL: "TDS Charges levied:",
  WITHDRAW_TO_ACCOUNT_DIRECTLY_LABEL: "Withdraw to your account directly",
  ENTER_OTP_LABEL: "Enter the OTP you recieved for withdrawal",
  WITHDRAW_INR_LABEL: "Withdraw INR",
  WITHDRAW_MODAL_TITLE: "Withdraw",
  BANK_ACCOUNT_NUMBER_LABEL: "Bank Account Number",
  BANK_ACCOUNT_IFSC_LABEL: "Bank Account IFSC Code",
  DEPOSIT_MODAL_LABEL: "Deposit",
  ENTER_REFERENCE_ID_LABEL: "Enter your Reference ID for the transaction",
  CUSTOMER_BANK_ACCOUNT_NUMBER_LABEL: "Your Bank Account Number:",
  NOTE: "Note:",
  BENEFICIARY_NOTE: "Please deposit the amount to below account number.",
  BENEFICIARY_ENTITY_LABEL: "Beneficiary Entity:",
  BENEFICIARY_ACCOUNT_NUMBER_LABEL: "Beneficiary Account Number:",
  BENEFICIARY_IFSC_LABEL: "Beneficiary IFSC Number:",
  BANK_ACCOUNT_TYPE_LABEL: "Bank Account Type:",
  DEPOSIT_INSTRUCTIONS_LABEL: "The amount should be deposited with above bank account only. Amount coming from any other bank account would be refunded back. *Payment through UPI is not allowed*",
  TRANSFER_TO_FUTURES_DIRECTLY_LABEL: "Transfer to USDT Wallet Directly",
  EXCEEDS_AVAILABLE_BALANCE_LABEL: "Amount exceeds available balance in your INR wallet",
  INR_EXCEEDS_AVAILABLE_BALANCE_LABEL: "Amount exceeds available balance in your INR wallet",
  AVAILABLE_BALANCE_LABEL: "Please check your Available Balance",
  NOT_EMPTY_LABEL: "Amount cannot be empty",
  MINIMUM_USDT_BUY_LABEL: "Minimum conversion amount at a time is {0} INR ",
  MAXIMUM_USDT_BUY_LABEL: "Maximum conversion amount at a time is {0} INR",
  OTP_NOT_EMPTY_LABEL: "OTP cannot be empty",
  SELL_USDT_SUCCESS_LABEL: "USDT Succesfully Sold. Please enter OTP to transfer to your bank account",
  WITHDRAW_INITIATED_LABEL: "Withdraw Initiated",
  MINIMUM_USDT_SELL_LABEL: "Minimum conversion amount is 1 USDT",
  MAXIMUM_USDT_SELL_LABEL: "Maximum conversion amount is 1000 USDT",
  EXCEEDS_AVAILABLE_BALANCE_USDT: "Amount exceeds available balance in your USDT wallet",
  CONFIRM_LABEL: "Confirm",
  CONTINUE_LABEL: "Continue",
  NOT_EMPTY_VALUE_LABEL: "Cannot be empty",
  MAXIMUM_DEPOSIT_AMOUNT_LABEL: "Maximum Deposit Amount Exceeded (< 500,000 INR)",
  MINIMUM_DEPOSIT_LABEL: "Minimum Deposit Amount = 500 INR",
  MINIMUM_WITHDRAW_AMOUNT_LABEL: "Minimum Withdrawable amount is 500 INR",
  MAXIMUM_WITHDRAW_AMOUNT_LABEL: "Maximum Withdrawable amount is 500000 INR",
  DEPOSIT_SUCCESS_LABEL: "Request for deposit amount of {0} INR with reference ID '{1}' has been submitted successfully. Please wait while we proccess your request. We appreciate your patience!",
  WITHDRAW_SUCCESS_MODAL: "Request for withdrawal amount of {0} INR has been submitted successfully. Please wait while we proccess your request. We appreciate your patience!",
  BUY_USDT_SUCCESS_MODAL: "Your purchase was successful. You have received {0} USDT in your wallet. Enjoy trading!",
  SELL_USDT_SUCCESS_MODAL: "Your have sold successfully. You received {0} USDT in your wallet. Keep hustling!",
  SELL_USDT_TO_BANK_ACCOUNT_SUCCESS_MODAL: "Your have sold successfully. You received {0} INR in your bank account. Keep hustling!",
  SELL_USDT_TO_BANK_ACCOUNT_MINIMUM_LABEL: "Minimum amount expected is {0} USDT",
  AMOUNT_NOT_NEGATIVE_LABEL: "Amount Cannot be Negative",
  TDS_AMOUNT_PERCENTAGE: 1,
  MINIMUM_USDT_BUY: 1,
  MINIMUM_USDT_SELL: 1,
  MINIMUM_INR_DEPOSIT: 500,
  MAXIMUM_INR_DEPOSIT: 500000,
  MINIMUM_INR_WITHDRAW: 500,
  MAXIMUM_INR_WITHDRAW: 500000
};
