name: Build and Test

on:
  pull_request:
    branches:
      - feature/MIGRATION

  workflow_dispatch:

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_BUILD_TYPE: development
      REACT_APP_PUBLIC_POSTHOG_KEY: "phc_gUZ99ORMqVlkoOYR7jiIy8k1ncp9HDzxyohW88CN6Sb"
      REACT_APP_PUBLIC_POSTHOG_URL: https://app.posthog.com"

    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FRONTEND_SUBMODULE_PAT }}
          submodules: recursive

      - name: Read submodule branch
        id: submodule
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.submoduleConfig

      - name: Checkout develop on all submodules
        run: |
          git submodule foreach git pull origin ${{ steps.submodule.outputs.content }}

      - name: Setup Node Env
        uses: actions/setup-node@v3.2.0

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Prettier Adjustment
        run: npm run prettier:write

      - name: Slack Notification Prettier
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ secrets.LOGO }}
          SLACK_USERNAME: Density Devops Bot
          SLACK_MESSAGE: Code Formatting ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}